### ISSUE TITLE
"adjusting volume" where?

### ISSUE THREAD

**Issue by kingio** [gordonturner/stupid-remote#7]
¿Where can i adjust volume?

**Comment by gordonturner** [comment]
Hey kingio, you have two options:

1. Use CEC
2. Use Lircd

For 1, you will need to setup and test your cec commands.

Please check:
http://www.cec-o-matic.com/

Your cec command will be something like:
10:44:41

Which is:
source, Recording 1
destination, System Audio Control, UI Command: Volume Up

This is an example, it will depend on your setup.

For 2, you will need to capture your tv remote (or if you are lucky it is already available) button presses for volume control.

Once you have the approach you want, you will have to setup the button(s) to call your commands, similar to the input switching that the app currently has setup.

**Comment by kingio** [comment]
oh, so it is different for each tv? i thought CEC was some sort of standard between all providers

**Comment by gordonturner** [comment]
The destination should be the same (assuming the audio is controlled by your tv of course), but the source will depend on what device you are sending it from.

I don't know what will happen if you send an incorrect source code, it might work, it might not.

**Comment by gordonturner** [comment]
Think of CEC as a network, with the different HDMI devices nodes on your network.

**Comment by gordonturner** [comment]
FYI, I did a blog post that might provide some help customizing and setting up:
https://blog.gordonturner.com/2016/12/19/stupid-remote-a-hdmi-cec-node-js-web-app/

Let me know if you need more help?  Otherwise I will close this issue.

**Comment by kingio** [comment]
TY! Closing issue
